import { Header, Container } from '@/shared/components';

import { Metadata } from 'next';
import { Suspense } from 'react';

export const metadata: Metadata = {
  title: 'Next Pizza | Корзина',
  description: 'Generated by Next.js',
};

export default function CheckoutLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className='min-h-screen bg-[#f3f3ee]'>
      <Container>
        <Suspense fallback={<div className='h-16' />}>
          <Header
            hasSearch={false}
            hasCart={false}
            className='border-b-gray-200'
          />
        </Suspense>
        <div className='w-full px-4 sm:px-6 lg:px-8 py-6'>
          <div className='max-w-5xl mx-auto'>{children}</div>
        </div>
      </Container>
    </main>
  );
}
