import { Header, Container, Categories } from '@/shared/components';

import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Next Pizza | Корзина',
  description: 'Generated by Next.js',
};

export default function CheckoutLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className='min-h-screen bg-[#f3f3ee]'>
      <Container>
        <Header
          hasSearch={false}
          hasCart={false}
          className='border-gray-200'
        />
        {children}
      </Container>
    </main>
  );
}
